"""
Django settings for mysite project.

Generated by 'django-admin startproject' using Django 2.0.8.

For more information on this file, see
https://docs.djangoproject.com/en/2.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.0/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
#BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Pre kontakt
# Build paths inside the project like this: BASE_DIR / 'subdir'
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'n069kq!wejc&v9mv8v9!bruaxqop$zyov&k#8q)m+s+u#jnh)e'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['127.0.0.1', '0.0.0.0',
                 '.pythonanywhere.com', '.herokuapp.com', ]

SITE_ID = 1     # suvisi to s django.contrib.sites

# Pridane kvoli prihlasovaniu sa miesto mena mailom
ACCOUNT_AUTHENTICATION_METHOD = 'email'
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_EMAIL_UNIQUE = True
# ACCOUNT_EMAIL_VERIFICATION = 'mandatory' lebo to suvisi s overenim na mail serveri


# EMAIL BACKENDS

# Pokial nastane pri registracii pomocou mailu chyba moy eto suvisiet
# s pouzivanim mailoveho servera. Osetri sa to pridanim tohoto v pripade
# osetrenia DEBUGU:
#if DEBUG:
#    EMAIL_BACKEND = 'django.core.mail.backends.dummy.EmailBackend'

# A keby bol fyzicky pouzity mailovy server, tak sa odkomentuje toto nizsie
# resp. sa sem daju udaje pre lokalneho klienta ako sme to urobili aj my:
'''
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'localhost'    # 'smtp.gmail.com'
EMAIL_PORT = 1025           # 587
EMAIL_HOST_USER = ''        # tokos1953@gmail.com
EMAIL_HOST_PASSWORD = ''    # najlepsie 16 znakovy string
EMAIL_USE_TLS = False       # True
'''
# Ale nemame sposob ako otestovat ci bol mail odoslany lebo sme pouzili testovaci
# ucet. Ak ale pouzijeme gmail tak nahrdime povodne udaje tym co je za nimi

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'mail.webglobe.sk'
EMAIL_PORT = 465
EMAIL_HOST_USER = 'info@comto.sk'
EMAIL_HOST_PASSWORD = '0207-Mama'
# EMAIL_USE_TLS = True
EMAIL_USE_SSL = True

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Application definition

AUTHENTICATION_BACKENDS = [
    # Needed to login by username in Django admin, regardless of `allauth`
    'django.contrib.auth.backends.ModelBackend',

    # `allauth` specific authentication methods, such as login by email
    'allauth.account.auth_backends.AuthenticationBackend',
]


INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'blog',

#   'django.contrib.sites,     keby som pouyil social napr. github
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    # ... include the providers you want to enable:
    # 'allauth.socialaccount.providers.github',
    'contact',
    'formular',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

    # Add the account middleware:
    "allauth.account.middleware.AccountMiddleware",
]

ROOT_URLCONF = 'mysite.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
#        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'DIRS': [],    # zmenene kvoli formularu
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                # `allauth` needs this from django
                'django.template.context_processors.request',
            ],
        },
    },
]

WSGI_APPLICATION = 'mysite.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'my_db',
        'USER' : 'postgres',
        'PASSWORD' : '03091953-Tomo',
        'HOST' : 'localhost',
        'PORT' : '5432',
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Africa/Nairobi'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.0/howto/static-files/

STATIC_URL = '/static/'
#STATIC_ROOT = os.path.join(BASE_DIR, 'static')

# Pre potreby kontaktov
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static")
]


# LOGIN_URL = '/admin/' toto bolo ale tiez nemuselo byt povodne

# Presmerúvate na cestu, ktorá je pripojená k aktuálnej adrese URL.
# Na presmerovanie na cestu, ktorá je pripojená ku koreňu domény.
# Musíte použiť úvodnú lomku.

LOGIN_REDIRECT_URL = '/'

                      
# Provider specific settings
SOCIALACCOUNT_PROVIDERS = {
    'google': {
        # For each OAuth based provider, either add a ``SocialApp``
        # (``socialaccount`` app) containing the required client
        # credentials, or list them here:
        'APP': {
            'client_id': '123',
            'secret': '456',
            'key': ''
        }
    }
# 'github': {
#        'APP': {
#            'client_id': '123',
#            'secret': '456',
#            'key': ''
#        }
}
